k=0:10;
a=[1 -0.7 0.1];
b=[7 -2];
f=0.4.^k;
filter(a,b,f);
h=impz(b,a,k);
g=stepz(b,a,length(k));
figure;
subplot(2,3,1);
plot(k,f,'r');
grid on;
title('零状态响应');
subplot(2,3,2);
stem(k,h,'g');
grid on;
title('单位取样响应的近似值');
subplot(2,2,3);
grid on;
stem(k,g,'b');
title('单位阶跃响应的近似值');
grid on;